import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // Constants for Footer props
  const currentYear = new Date().getFullYear();
  const email = "hello@example.com";
  const artistName = "John Doe";
  const artPageLink = "/draw";

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        

        {children}
        
        <Footer 
          currentYear={currentYear}
          email={email}
          artistName={artistName}
          artPageLink={artPageLink}
        />

      </body>
    </html>
  );
}
